POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"phuc",
    "password":"123"
}
################################


POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDlkMTJiNDE0NmNlMjQ2YjRlN2JhM2IiLCJpYXQiOjE2MjExMzQyNzd9.mWRYrnR_lhxqWjnK4V8U3c0HpTJ5IUV8VwnAYlQtlfs



{
    "title": "huu",
    "discription": "node index",
    "status": "TO LEARN"
    
}